global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 30s
  external_labels:
    prometheus: monitoring/k8s
    prometheus_replica: prometheus-k8s-0
remote_write:
  - url: "http://m3coordinator-m3db-cluster.default.svc:7201/api/v1/prom/remote/write"
scrape_configs:
- job_name: grafana
  kubernetes_sd_configs:
  - role: pod
    namespaces:
      names:
      - default
      - kube-system
      - monitoring
      - loki
