// Code generated by lister-gen. DO NOT EDIT.

package v1

// M3DBClusterListerExpansion allows custom methods to be added to
// M3DBClusterLister.
type M3DBClusterListerExpansion interface{}

// M3DBClusterNamespaceListerExpansion allows custom methods to be added to
// M3DBClusterNamespaceLister.
type M3DBClusterNamespaceListerExpansion interface{}
