// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/m3db/m3db-operator/pkg/apis/m3dboperator/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// M3DBClusterLister helps list M3DBClusters.
type M3DBClusterLister interface {
	// List lists all M3DBClusters in the indexer.
	List(selector labels.Selector) (ret []*v1.M3DBCluster, err error)
	// M3DBClusters returns an object that can list and get M3DBClusters.
	M3DBClusters(namespace string) M3DBClusterNamespaceLister
	M3DBClusterListerExpansion
}

// m3DBClusterLister implements the M3DBClusterLister interface.
type m3DBClusterLister struct {
	indexer cache.Indexer
}

// NewM3DBClusterLister returns a new M3DBClusterLister.
func NewM3DBClusterLister(indexer cache.Indexer) M3DBClusterLister {
	return &m3DBClusterLister{indexer: indexer}
}

// List lists all M3DBClusters in the indexer.
func (s *m3DBClusterLister) List(selector labels.Selector) (ret []*v1.M3DBCluster, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.M3DBCluster))
	})
	return ret, err
}

// M3DBClusters returns an object that can list and get M3DBClusters.
func (s *m3DBClusterLister) M3DBClusters(namespace string) M3DBClusterNamespaceLister {
	return m3DBClusterNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// M3DBClusterNamespaceLister helps list and get M3DBClusters.
type M3DBClusterNamespaceLister interface {
	// List lists all M3DBClusters in the indexer for a given namespace.
	List(selector labels.Selector) (ret []*v1.M3DBCluster, err error)
	// Get retrieves the M3DBCluster from the indexer for a given namespace and name.
	Get(name string) (*v1.M3DBCluster, error)
	M3DBClusterNamespaceListerExpansion
}

// m3DBClusterNamespaceLister implements the M3DBClusterNamespaceLister
// interface.
type m3DBClusterNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all M3DBClusters in the indexer for a given namespace.
func (s m3DBClusterNamespaceLister) List(selector labels.Selector) (ret []*v1.M3DBCluster, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.M3DBCluster))
	})
	return ret, err
}

// Get retrieves the M3DBCluster from the indexer for a given namespace and name.
func (s m3DBClusterNamespaceLister) Get(name string) (*v1.M3DBCluster, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1.Resource("m3dbcluster"), name)
	}
	return obj.(*v1.M3DBCluster), nil
}
