env:
  global:
    - TEST_TIMEOUT_SCALE=20 # Set higher timeouts for Travis
    - PACKAGE=github.com/$TRAVIS_REPO_SLUG
    - CHANGE_MINIKUBE_NONE_USER=true

dist: trusty

sudo: required

before_script:
- ./build/ci-install-minikube.sh

script:
 - ./build/ci-test-minikube.sh

services:
  - docker
