FROM golang:1.18-stretch

RUN mkdir /helm && \
  cd /helm && \
  wget -q -O helm.tgz https://get.helm.sh/helm-v3.0.2-linux-amd64.tar.gz && \
  tar xzvf helm.tgz && \
  mv linux-amd64/helm /bin && \
  rm -rf /helm
