common: &common
  timeout_in_minutes: 20
  agents:
    queue: workers
  retry:
    # Automatically retry failures one time.
    automatic:
      limit: 1
    # Allow manual retries.
    manual: true

steps:
  - name: "Check for :docker: build"
    command: ".ci/docker/check_do_docker.sh"
    agents:
      queue: init
    timeout_in_minutes: 10
    retry:
      automatic:
        limit: 1
      manual: true
  - name: Unit
    command: .buildkite/test.sh
    plugins:
      docker-compose#v2.5.1:
        run: app
        config: .buildkite/docker-compose.yml
        workdir: /go/src/github.com/m3db/m3db-operator
    <<: *common
  # NB(schallert): skipped until OSS CI stack upgraded
  # - name: ":kubernetes: e2e tests"
  #   command: make clean test-e2e
  #   env:
  #     CGO_ENABLED: 0
  #     GIMME_GO_VERSION: 1.13.x
  #   plugins:
  #     gopath-checkout#v1.0.1:
  #       import: github.com/m3db/m3db-operator
  #   <<: *common
