steps:
  - name: ":kubernetes: e2e tests"
    command: make clean test-e2e
    env:
      CGO_ENABLED: 0
      GIMME_GO_VERSION: 1.13.x
    plugins:
      gopath-checkout#v1.0.1:
        import: github.com/m3db/m3db-operator
    timeout_in_minutes: 20
    agents:
      queue: default
    retry:
      automatic:
        limit: 1
      manual: true
