common: &common
  timeout_in_minutes: 20
  agents:
    queue: workers
  retry:
    # Automatically retry failures one time.
    automatic:
      limit: 1
    # Allow manual retries.
    manual: true

steps:
  - name: "Check for :docker: build"
    command: ".ci/docker/check_do_docker.sh"
    agents:
      queue: init
    timeout_in_minutes: 10
    retry:
      automatic:
        limit: 1
      manual: true
  - name: Unit
    command: .buildkite/test.sh
    plugins:
      docker-compose#v2.5.1:
        run: app
        config: .buildkite/docker-compose.yml
        workdir: /go/src/github.com/m3db/m3db-operator
    <<: *common
