coordinator:
  carbon:
    ingester:
      listenAddress: "0.0.0.0:7204"

db:
  hostID:
    resolver: file
    file:
      path: /etc/m3db/pod-identity/identity
      timeout: 5m

  client:
    writeConsistencyLevel: majority
    readConsistencyLevel: unstrict_majority

  discovery:
    config:
      service:
        env: default_env
        zone: embedded
        service: m3db
        cacheDir: /var/lib/m3kv
        etcdClusters:
        - zone: embedded
          endpoints:
          - http://etcd-0.etcd:2379
          - http://etcd-1.etcd:2379
          - http://etcd-2.etcd:2379