coordinator:
  listenAddress: "0.0.0.0:7201"
  local:
    namespaces:
      - namespace: default
        type: unaggregated
        retention: 48h
  logging:
    level: info
  metrics:
    scope:
      prefix: "coordinator"
    prometheus:
      handlerPath: /metrics
      listenAddress: 0.0.0.0:7203
    sanitization: prometheus
    samplingRate: 1.0
    extended: none
  tagOptions:
    idScheme: quoted
  carbon:
    ingester:
      listenAddress: "0.0.0.0:7204"

db:
  logging:
    level: info

  metrics:
    prometheus:
      handlerPath: /metrics
    sanitization: prometheus
    samplingRate: 1.0
    extended: detailed

  listenAddress: 0.0.0.0:9000
  clusterListenAddress: 0.0.0.0:9001
  httpNodeListenAddress: 0.0.0.0:9002
  httpClusterListenAddress: 0.0.0.0:9003
  debugListenAddress: 0.0.0.0:9004

  hostID:
    resolver: file
    file:
      path: /etc/m3db/pod-identity/identity
      timeout: 5m

  client:
    writeConsistencyLevel: majority
    readConsistencyLevel: unstrict_majority

  gcPercentage: 100

  writeNewSeriesAsync: true
  writeNewSeriesLimitPerSecond: 1048576
  writeNewSeriesBackoffDuration: 2ms

  bootstrap:
    filesystem:
      numProcessorsPerCPU: 0.125
    # https://docs.m3db.io/operational_guide/availability_consistency_durability/
    commitlog:
      returnUnfulfilledForCorruptCommitLogFiles: false

  commitlog:
    flushMaxBytes: 524288
    flushEvery: 1s
    queue:
      calculationType: fixed
      size: 2097152

  filesystem:
    filePathPrefix: /var/lib/m3db

  discovery:
    config:
      service:
        env: default_env
        zone: embedded
        service: m3db
        cacheDir: /var/lib/m3kv
        etcdClusters:
        - zone: embedded
          endpoints:
          - http://etcd-0.etcd:2379
          - http://etcd-1.etcd:2379
          - http://etcd-2.etcd:2379