apiVersion: operator.m3db.io/v1alpha1
kind: M3DBCluster
metadata:
  name: m3db-cluster-test-1
spec:
  image: quay.io/m3db/m3dbnode:latest
  replicationFactor: 3
  numberOfShards: 256
  etcdEndpoints:
  - http://etcd-0.etcd:2379
  - http://etcd-1.etcd:2379
  - http://etcd-2.etcd:2379
  isolationGroups:
    - name: us-east1-b
      numInstances: 1
    - name: us-east1-c
      numInstances: 1
    - name: us-east1-d
      numInstances: 1
  namespaces:
    - name: metrics-10s:2d
      preset: 10s:2d
  containerResources:
    requests:
      memory: 4Gi
      cpu: '1'
    limits:
      memory: 12Gi
      cpu: '4'
