// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	internalinterfaces "github.com/m3db/m3db-operator/pkg/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// M3DBClusters returns a M3DBClusterInformer.
	M3DBClusters() M3DBClusterInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// M3DBClusters returns a M3DBClusterInformer.
func (v *version) M3DBClusters() M3DBClusterInformer {
	return &m3DBClusterInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
